/**
 * EchoKind Default Verified Community Aid Requests
 * Used for automated self-healing & persistent database seeding
 */

export const DEFAULT_AID_REQUESTS = [
  {
    id: 'req-001',
    title: 'Warm Winter Coats & Thermal Boots for Ward 4 Children',
    description: 'Temperatures in northern Detroit are expected to drop below freezing next week. Our grassroots community youth center is providing 35 elementary school children with warm winter jackets, waterproof boots, and thermal gloves so they can safely walk to school and play outdoors.',
    authorName: 'Marcus Vance',
    authorRole: 'Community Youth Director',
    location: 'Detroit, Michigan, USA',
    coordinates: { lat: 42.3314, lng: -83.0458 },
    nonprofitName: 'Feeding America / Detroit Youth Resilience',
    nonprofitEin: '36-3673599',
    is501c3Verified: true,
    recipientWallet: 'Dqv5yZzi8vN2TGsQ966CebKnsvBf12PXJEcvFTHdx1xu',
    climateData: {
      temperatureC: 1.5,
      temperatureF: 34.7,
      apparentTemperatureC: -2.1,
      humidity: 82,
      precipitationMm: 0,
      windSpeedKmh: 16.5,
      weatherCondition: 'Cold & Overcast',
      weatherCode: 3,
      alertBadge: 'Autumn Freeze Watch',
      alertLevel: 'none',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Shelter & Warmth',
    unTheme: 'Equity & Inclusion',
    urgency: 'urgent',
    status: 'active',
    targetAmountSOL: 4.5,
    raisedAmountSOL: 3.2,
    donorCount: 18,
    itemsNeeded: [
      { id: 'i-1', name: 'Youth Insulated Parkas (Sizes S-L)', quantity: 35, unit: 'coats', fulfilled: true, estimatedCostUSD: 1400 },
      { id: 'i-2', name: 'Waterproof Winter Boots', quantity: 35, unit: 'pairs', fulfilled: false, estimatedCostUSD: 1050 },
      { id: 'i-3', name: 'Thermal Glove & Beanie Sets', quantity: 50, unit: 'sets', fulfilled: true, estimatedCostUSD: 500 }
    ],
    voiceNarrationText: "Hello neighbors. Winter hits hard here on the north side, and no 8-year-old should ever have to wait at a snowy bus stop in just a hoodie. With your generous micro-grants and supply drops, we've already secured 35 parkas. We just need boots to keep these young feet dry and warm.",
    audioDurationSec: 24,
    imageUrl: 'https://images.unsplash.com/photo-1543083477-4f785aeafaa9?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-09-02T10:15:00Z',
    tags: ['Youth', 'Winter Relief', 'School Aid', 'Grassroots']
  },
  {
    id: 'req-002',
    title: 'Emergency Solar Backup Battery for Appalachian Mountain Clinic',
    description: 'Following severe flash flooding that damaged grid infrastructure in Eastern Kentucky, our volunteer-run rural clinic requires a portable 2.4kWh LiFePO4 solar generator to keep insulin, pediatric antibiotics, and nebulizers continuously chilled during prolonged outages.',
    authorName: 'Dr. Clara Higgins',
    authorRole: 'Volunteer Physician & Nurse Lead',
    location: 'Hazard, Kentucky, USA',
    coordinates: { lat: 37.2498, lng: -83.1932 },
    nonprofitName: 'Direct Relief / Rural Health Initiative',
    nonprofitEin: '95-1831116',
    is501c3Verified: true,
    recipientWallet: '2VyJghegXGD7rPxS5HzemSWWjv64N8v8bThJoMRmTeEs',
    climateData: {
      temperatureC: 14.8,
      temperatureF: 58.6,
      apparentTemperatureC: 13.5,
      humidity: 91,
      precipitationMm: 3.4,
      windSpeedKmh: 12.0,
      weatherCondition: 'Heavy Rain Showers',
      weatherCode: 81,
      alertBadge: 'Flash Flood Recovery Watch',
      alertLevel: 'storm_warning',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Healthcare & Medicine',
    unTheme: 'Climate & Poverty',
    urgency: 'urgent',
    status: 'active',
    targetAmountSOL: 6.8,
    raisedAmountSOL: 5.1,
    donorCount: 31,
    itemsNeeded: [
      { id: 'i-4', name: 'Portable LiFePO4 Solar Power Station (2400Wh)', quantity: 1, unit: 'unit', fulfilled: true, estimatedCostUSD: 1600 },
      { id: 'i-5', name: 'Foldable 400W Solar Panels', quantity: 2, unit: 'panels', fulfilled: false, estimatedCostUSD: 700 },
      { id: 'i-6', name: 'Medical Cold-Chain Thermometer Sensors', quantity: 4, unit: 'sensors', fulfilled: true, estimatedCostUSD: 240 }
    ],
    voiceNarrationText: "When the creeks rise and power lines snap across these hollows, refrigerated insulin spoils within 36 hours. Our little clinic is the only medical post within 40 miles. Having portable solar backup isn't a luxury—it keeps our diabetic elders alive through the flood recovery.",
    audioDurationSec: 28,
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-09-03T08:30:00Z',
    tags: ['Flood Relief', 'Medical Aid', 'Clean Energy', 'Rural Health']
  },
  {
    id: 'req-003',
    title: 'Refurbished Laptops for First-Generation Girls STEM Academy',
    description: 'We run an intensive 12-week coding and electronics workshop for 24 high-school girls in Nairobi informal settlements. We are sourcing certified refurbished laptops and microcontroller starter kits to equip each student with their own learning workstation.',
    authorName: 'Amina Omondi',
    authorRole: 'Founder & Tech Educator',
    location: 'Nairobi, Kenya',
    coordinates: { lat: -1.2921, lng: 36.8219 },
    nonprofitName: 'World Central Kitchen Inc. / STEM Nutrition',
    nonprofitEin: '27-3521132',
    is501c3Verified: true,
    recipientWallet: '7nuCn1x9RRGj9yhWPa8WwSVneJdMqU4tHHPsfdr3A17t',
    climateData: {
      temperatureC: 24.2,
      temperatureF: 75.6,
      apparentTemperatureC: 23.8,
      humidity: 55,
      precipitationMm: 0,
      windSpeedKmh: 14.2,
      weatherCondition: 'Partly Cloudy',
      weatherCode: 2,
      alertBadge: 'Stable STEM Field Weather',
      alertLevel: 'none',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Education & Tech',
    unTheme: 'Youth Leadership',
    urgency: 'moderate',
    status: 'active',
    targetAmountSOL: 7.2,
    raisedAmountSOL: 4.8,
    donorCount: 26,
    itemsNeeded: [
      { id: 'i-7', name: 'Refurbished ThinkPad Laptops (Core i5/16GB)', quantity: 12, unit: 'laptops', fulfilled: false, estimatedCostUSD: 2400 },
      { id: 'i-8', name: 'ESP32 IoT & Robotics Starter Packs', quantity: 24, unit: 'kits', fulfilled: true, estimatedCostUSD: 720 },
      { id: 'i-9', name: '6-Month High-Speed Mesh WiFi Subsidy', quantity: 1, unit: 'service', fulfilled: true, estimatedCostUSD: 360 }
    ],
    voiceNarrationText: "Talent is everywhere, but hardware is not. When you put a code terminal in the hands of a curious 16-year-old girl, she doesn't just learn Python—she builds flood sensors and agricultural trackers for her own neighborhood. Your generosity directly sparks the next generation of African innovators.",
    audioDurationSec: 26,
    imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-09-01T14:20:00Z',
    tags: ['Girls In Tech', 'STEM', 'Digital Inclusion', 'Education']
  },
  {
    id: 'req-004',
    title: 'Fresh Farm Produce Rescue & Community Solidarity Kitchen',
    description: 'Every Saturday, our team rescues 800+ lbs of surplus organic vegetables from regional farmers that would otherwise be discarded. We cook 250 hot, nutritious plant-forward meals and distribute fresh grocery boxes directly to low-income families and unhoused neighbors.',
    authorName: 'Elena Rostova',
    authorRole: 'Food Sovereignty Coordinator',
    location: 'Oakland, California, USA',
    coordinates: { lat: 37.8044, lng: -122.2712 },
    nonprofitName: 'Feeding America / Urban Farm Recovery',
    nonprofitEin: '36-3673599',
    is501c3Verified: true,
    recipientWallet: 'D4MKCKqZTABJzneg5JiMxg2RqkBhdwcPWny92uVNomyH',
    climateData: {
      temperatureC: 19.4,
      temperatureF: 66.9,
      apparentTemperatureC: 19.0,
      humidity: 62,
      precipitationMm: 0,
      windSpeedKmh: 15.0,
      weatherCondition: 'Clear Sky',
      weatherCode: 0,
      alertBadge: 'Optimal Distribution Weather',
      alertLevel: 'none',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Food & Nutrition',
    unTheme: 'Ethical Giving',
    urgency: 'ongoing',
    status: 'fulfilled',
    targetAmountSOL: 3.5,
    raisedAmountSOL: 3.5,
    donorCount: 42,
    itemsNeeded: [
      { id: 'i-10', name: 'Commercial Grade Stainless Food Warmers', quantity: 2, unit: 'units', fulfilled: true, estimatedCostUSD: 600 },
      { id: 'i-11', name: 'Compostable Takeout Meal Containers', quantity: 1000, unit: 'boxes', fulfilled: true, estimatedCostUSD: 350 },
      { id: 'i-12', name: 'Refrigerated Cargo Van Fuel Grant (Month)', quantity: 1, unit: 'grant', fulfilled: true, estimatedCostUSD: 450 }
    ],
    voiceNarrationText: "Food waste is a moral failure when families are going to bed hungry two blocks away. We bridge that gap with dignifying, home-cooked hot meals and zero bureaucracy. We thank every generous soul who funded our fuel and warmers this month—we are 100% funded!",
    audioDurationSec: 22,
    imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-08-30T11:00:00Z',
    tags: ['Food Rescue', 'Zero Waste', 'Solidarity Kitchen', 'Nutrition'],
    proofConfidenceScore: 98,
    receiptDetails: {
      storeName: 'Berkeley Bowl Produce & Organic Distribution Depot',
      receiptDate: '2026-09-04 11:30',
      currency: 'USD',
      totalUSD: 450,
      lineItems: [
        {
          description: 'Commercial Grade Stainless Food Warmers',
          qty: 2,
          unitPriceUSD: 300,
          totalUSD: 600,
          matchedTicketItem: 'Commercial Grade Stainless Food Warmers',
          matchScore: 99
        },
        {
          description: 'Compostable Takeout Containers (Bulk 1000)',
          qty: 1000,
          unitPriceUSD: 0.35,
          totalUSD: 350,
          matchedTicketItem: 'Compostable Takeout Meal Containers',
          matchScore: 98
        }
      ]
    }
  },
  {
    id: 'req-005',
    title: 'Tactile Audio Learning Kits & Refreshable Braille Tablets',
    description: 'Providing blind and visually impaired children in under-resourced public school districts with specialized tactile audio tablets, 3D printed topographic maps, and audio-described science kits to ensure equal classroom participation.',
    authorName: 'Samira Chen',
    authorRole: 'Assistive Tech Specialist',
    location: 'Austin, Texas, USA',
    coordinates: { lat: 30.2672, lng: -97.7431 },
    nonprofitName: 'United Nations Foundation / Humanitarian Response',
    nonprofitEin: '95-1831116',
    is501c3Verified: true,
    recipientWallet: '4aoR48sXEwyWEh9eUKzGV536CZzwSocHP5MAsX8WWJvD',
    climateData: {
      temperatureC: 28.5,
      temperatureF: 83.3,
      apparentTemperatureC: 29.8,
      humidity: 60,
      precipitationMm: 0,
      windSpeedKmh: 11.2,
      weatherCondition: 'Sunny',
      weatherCode: 1,
      alertBadge: 'Clear Weather',
      alertLevel: 'none',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Education & Tech',
    unTheme: 'Equity & Inclusion',
    urgency: 'moderate',
    status: 'active',
    targetAmountSOL: 5.4,
    raisedAmountSOL: 2.1,
    donorCount: 14,
    itemsNeeded: [
      { id: 'i-13', name: 'Portable Tactile Audio Keyboards', quantity: 6, unit: 'devices', fulfilled: false, estimatedCostUSD: 1800 },
      { id: 'i-14', name: '3D Printed Tactile Science Anatomy Models', quantity: 12, unit: 'sets', fulfilled: true, estimatedCostUSD: 480 },
      { id: 'i-15', name: 'Bone Conduction Learning Headsets', quantity: 8, unit: 'headsets', fulfilled: false, estimatedCostUSD: 640 }
    ],
    voiceNarrationText: "Imagine sitting in a science classroom where the teacher points at a diagram on the whiteboard, and you can only listen to silence. Tactile models and audio descriptions unlock the universe for visually impaired kids. Every small pledge helps us put these sensory tools into little hands.",
    audioDurationSec: 25,
    imageUrl: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-09-02T16:45:00Z',
    tags: ['Accessibility', 'Braille', 'Visual Impairment', 'Assistive Tech']
  },
  {
    id: 'req-006',
    title: 'Volunteer Cargo Bike Courier Network for Isolated Seniors',
    description: 'Our youth volunteer cargo-cyclists deliver essential medications, heating oil vouchers, and fresh groceries to elderly, mobility-impaired residents living alone in high-rise council estates.',
    authorName: 'Oliver Wright',
    authorRole: 'Community Dispatcher',
    location: 'Leeds, West Yorkshire, UK',
    coordinates: { lat: 53.8008, lng: -1.5491 },
    nonprofitName: 'United Nations Foundation / Humanitarian Response',
    nonprofitEin: '95-1831116',
    is501c3Verified: true,
    recipientWallet: 'Afoem182Bdp1HK2ntS6iQQWkx1Wd8MBFLD2nkGpaWQAq',
    climateData: {
      temperatureC: 12.1,
      temperatureF: 53.8,
      apparentTemperatureC: 10.5,
      humidity: 85,
      precipitationMm: 0.8,
      windSpeedKmh: 20.4,
      weatherCondition: 'Light Rain / Drizzle',
      weatherCode: 51,
      alertBadge: 'Precipitation Active',
      alertLevel: 'none',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Community Tools',
    unTheme: 'Tech-Driven Giving',
    urgency: 'ongoing',
    status: 'fulfilled',
    targetAmountSOL: 2.8,
    raisedAmountSOL: 2.8,
    donorCount: 22,
    itemsNeeded: [
      { id: 'i-16', name: 'Heavy-Duty Cargo Bike Trailer', quantity: 2, unit: 'trailers', fulfilled: true, estimatedCostUSD: 800 },
      { id: 'i-17', name: 'Insulated Medicine Delivery Panniers', quantity: 4, unit: 'bags', fulfilled: true, estimatedCostUSD: 320 }
    ],
    voiceNarrationText: "For many of our elderly neighbors, our volunteer courier is the only friendly voice they hear all week. Thanks to the EchoKind community, our cargo trailers were completely funded! We delivered 84 grocery packages and prescriptions in the last 7 days alone.",
    audioDurationSec: 21,
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
    verifiedProofImageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=80',
    proofNotes: 'All 2 cargo trailers delivered and assembled. First 84 deliveries logged and verified on-chain.',
    proofConfidenceScore: 98,
    createdAt: '2026-08-25T09:00:00Z',
    tags: ['Senior Care', 'Cargo Bikes', 'Mutual Aid', 'Loneliness Relief']
  },
  {
    id: 'req-007',
    title: 'Cocina Solidaria en East LA: Fresh Produce & Warm Meals',
    description: 'Nuestra cocina comunitaria en el este de Los Ángeles necesita 30 cajas de verduras frescas, arroz y frijoles para 45 familias trabajadoras durante los meses de invierno.',
    authorName: 'Maricela Hernandez',
    authorRole: 'Coordinadora Comunitaria',
    location: 'East Los Angeles, California, USA',
    coordinates: { lat: 34.0224, lng: -118.1670 },
    nonprofitName: 'Direct Relief',
    nonprofitEin: '95-1831116',
    is501c3Verified: true,
    recipientWallet: '6esP1E63SSeQsTkMAzqBB2YrZrLAD59PcwPhva89K1RX',
    originalLanguage: 'es-US',
    originalLanguageLabel: 'Español',
    originalTranscript: 'Nuestra cocina comunitaria en el este de Los Ángeles necesita 30 cajas de verduras frescas, arroz y frijoles para 45 familias trabajadoras.',
    voiceNarrationOriginal: 'Nuestra cocina comunitaria en el este de Los Ángeles necesita 30 cajas de verduras frescas, arroz y frijoles para 45 familias trabajadoras.',
    voiceNarrationEnglish: 'Our community kitchen in East Los Angeles urgently needs 30 fresh vegetable crates, beans, and rice to support 45 farmworker families.',
    climateData: {
      temperatureC: 22.4,
      temperatureF: 72.3,
      apparentTemperatureC: 22.0,
      humidity: 58,
      precipitationMm: 0,
      windSpeedKmh: 9.8,
      weatherCondition: 'Sunny',
      weatherCode: 1,
      alertBadge: 'Clear Skies',
      alertLevel: 'none',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Food & Nutrition',
    unTheme: 'Ethical Giving',
    urgency: 'urgent',
    status: 'active',
    targetAmountSOL: 3.6,
    raisedAmountSOL: 2.1,
    donorCount: 28,
    itemsNeeded: [
      { id: 'i-18', name: 'Fresh Farm Vegetable Crates (Bulk)', quantity: 30, unit: 'crates', fulfilled: true, estimatedCostUSD: 600 },
      { id: 'i-19', name: 'Staple Pinto Beans & Jasmine Rice (50lb bags)', quantity: 15, unit: 'sacks', fulfilled: false, estimatedCostUSD: 450 },
      { id: 'i-20', name: 'Commercial Soup Storage Containers', quantity: 20, unit: 'carriers', fulfilled: true, estimatedCostUSD: 320 }
    ],
    voiceNarrationText: 'Our community kitchen in East Los Angeles urgently needs 30 fresh vegetable crates, beans, and rice to support 45 farmworker families.',
    audioDurationSec: 23,
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-09-04T12:00:00Z',
    tags: ['Solidaridad', 'MutualAid', 'FoodSecurity', 'LatinxSupport']
  },
  {
    id: 'req-008',
    title: 'Kharkiv Civilian Winter Resilience: Sub-Zero Emergency Warmth',
    description: 'Наша волонтерська група у Харкові терміново потребує 35 теплих ковдр та автономних обігрівачів для сімей перед настанням морозів.',
    authorName: 'Yaroslav Bondarenko',
    authorRole: 'Civilian Defense Relief Volunteer',
    location: 'Kharkiv, Ukraine',
    coordinates: { lat: 49.9935, lng: 36.2304 },
    nonprofitName: 'Direct Relief / Ukraine Emergency Response',
    nonprofitEin: '95-1831116',
    is501c3Verified: true,
    recipientWallet: '4P8DizCXxQJFHWU7BHJztDcQpD9B2Qz9r7tD2u9qsVPG',
    originalLanguage: 'uk-UA',
    originalLanguageLabel: 'Українська',
    originalTranscript: 'Наша волонтерська група у Харкові терміново потребує 35 теплих ковдр та автономних обігрівачів для сімей перед настанням морозів.',
    voiceNarrationOriginal: 'Наша волонтерська група у Харкові терміново потребує 35 теплих ковдр та автономних обігрівачів для сімей перед настанням морозів.',
    voiceNarrationEnglish: 'Our volunteer group in Kharkiv urgently needs 35 heavy thermal blankets and portable space heaters for families in damaged homes before severe freeze sets in.',
    climateData: {
      temperatureC: -14.2,
      temperatureF: 6.4,
      apparentTemperatureC: -19.1,
      humidity: 89,
      precipitationMm: 2.8,
      windSpeedKmh: 24.5,
      weatherCondition: 'Heavy Snow / Ice Fog',
      weatherCode: 73,
      alertBadge: 'Sub-Zero Freeze Crisis (-14.2°C)',
      alertLevel: 'cold_freeze',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Shelter & Warmth',
    unTheme: 'Climate & Poverty',
    urgency: 'urgent',
    status: 'active',
    targetAmountSOL: 5.2,
    raisedAmountSOL: 3.4,
    donorCount: 39,
    itemsNeeded: [
      { id: 'i-21', name: 'Sub-Zero Thermal Blankets (Heavy Fleece)', quantity: 35, unit: 'blankets', fulfilled: true, estimatedCostUSD: 1050 },
      { id: 'i-22', name: 'Diesel / Electric Space Heaters (2kW)', quantity: 5, unit: 'units', fulfilled: false, estimatedCostUSD: 1250 },
      { id: 'i-23', name: 'Power Bank Station for Phone Charging', quantity: 8, unit: 'stations', fulfilled: true, estimatedCostUSD: 400 }
    ],
    voiceNarrationText: 'Our volunteer group in Kharkiv urgently needs 35 heavy thermal blankets and portable space heaters for families in damaged homes before severe freeze sets in.',
    audioDurationSec: 25,
    imageUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-09-04T15:30:00Z',
    tags: ['UkraineAid', 'WinterEmergency', 'Humanitarian', 'FreezeRelief']
  },
  {
    id: 'req-009',
    title: 'Banque Alimentaire et Vêtements Chauds pour Montréal',
    description: 'Notre refuge communautaire à Montréal a un besoin urgent de 40 manteaux d’hiver épais, de bottes thermiques et de denrées non périssables pour soutenir les familles vulnérables avant la vague de froid extrême.',
    authorName: 'Jean-Luc Tremblay',
    authorRole: 'Coordonnateur d’Aide d’Urgence',
    location: 'Montreal, Quebec, Canada',
    coordinates: { lat: 45.5017, lng: -73.5673 },
    nonprofitName: 'Direct Relief / Canada Aid',
    nonprofitEin: '95-1831116',
    is501c3Verified: true,
    recipientWallet: 'J5Q5PG75xeeFecNriPj4FEXuK5qcVz6sZjYTDh2rpZDG',
    originalLanguage: 'fr-CA',
    originalLanguageLabel: 'Français',
    originalTranscript: 'Notre refuge communautaire à Montréal a un besoin urgent de 40 manteaux d’hiver épais et de denrées alimentaires.',
    voiceNarrationOriginal: 'Notre refuge communautaire à Montréal a un besoin urgent de 40 manteaux d’hiver épais, de bottes thermiques et de denrées non périssables pour soutenir les familles vulnérables.',
    voiceNarrationEnglish: 'Our community shelter in Montreal urgently needs 40 insulated winter coats, thermal boots, and staple groceries for vulnerable families before the sub-zero freeze.',
    voiceNarrationText: 'Our community shelter in Montreal urgently needs 40 insulated winter coats, thermal boots, and staple groceries for vulnerable families before the sub-zero freeze.',
    climateData: {
      temperatureC: -8.5,
      temperatureF: 16.7,
      apparentTemperatureC: -14.2,
      humidity: 78,
      precipitationMm: 1.2,
      windSpeedKmh: 22.0,
      weatherCondition: 'Snow Flurries',
      weatherCode: 71,
      alertBadge: 'Sub-Zero Canadian Freeze (-8.5°C)',
      alertLevel: 'cold_freeze',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Shelter & Warmth',
    unTheme: 'Climate & Poverty',
    urgency: 'urgent',
    status: 'active',
    targetAmountSOL: 4.0,
    raisedAmountSOL: 2.8,
    donorCount: 24,
    itemsNeeded: [
      { id: 'i-24', name: 'Manteaux Thermiques / Heavy Parkas', quantity: 40, unit: 'coats', fulfilled: true, estimatedCostUSD: 1600 },
      { id: 'i-25', name: 'Bottes d’Hiver Imperméables', quantity: 30, unit: 'pairs', fulfilled: false, estimatedCostUSD: 900 }
    ],
    audioDurationSec: 22,
    imageUrl: 'https://images.unsplash.com/photo-1516431883659-655d41c09bf9?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-09-05T09:15:00Z',
    tags: ['MontrealAid', 'WinterRelief', 'Solidarite', 'Refuge']
  },
  {
    id: 'req-010',
    title: 'إغاثة طبية عاجلة ومستلزمات أطفال في بيروت (Emergency Pediatric Aid)',
    description: 'فريق الإغاثة الأهلي في بيروت بحاجة ماسة إلى أدوية أطفال، حليب رضع، ومولدات طاقة شمسية لتشغيل حضانات الرضع في المستوصف الخيري.',
    authorName: 'Nour El-Khoury',
    authorRole: 'مديرة الإغاثة الإنسانية',
    location: 'Beirut, Lebanon',
    coordinates: { lat: 33.8938, lng: 35.5018 },
    nonprofitName: 'United Nations Foundation / Humanitarian Response',
    nonprofitEin: '95-1831116',
    is501c3Verified: true,
    recipientWallet: 'CPDZcAs36XSyWQLqrkg3htNkHEpdLQ9GGyD6Fhgji2Wm',
    originalLanguage: 'ar-LB',
    originalLanguageLabel: 'العربية',
    originalTranscript: 'فريق الإغاثة الأهلي في بيروت بحاجة ماسة إلى أدوية أطفال، حليب رضع، ومولدات طاقة شمسية.',
    voiceNarrationOriginal: 'فريق الإغاثة الأهلي في بيروت بحاجة ماسة إلى أدوية أطفال، حليب رضع، ومولدات طاقة شمسية لتشغيل حضانات الرضع في المستوصف الخيري.',
    voiceNarrationEnglish: 'Our volunteer relief clinic in Beirut urgently needs pediatric medicines, infant formula, and solar battery backup to power incubators during power grid outages.',
    voiceNarrationText: 'Our volunteer relief clinic in Beirut urgently needs pediatric medicines, infant formula, and solar battery backup to power incubators during power grid outages.',
    climateData: {
      temperatureC: 26.8,
      temperatureF: 80.2,
      apparentTemperatureC: 28.1,
      humidity: 68,
      precipitationMm: 0,
      windSpeedKmh: 14.0,
      weatherCondition: 'Clear & Warm',
      weatherCode: 1,
      alertBadge: 'Urgent Medical Need',
      alertLevel: 'none',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Healthcare & Medicine',
    unTheme: 'Equity & Inclusion',
    urgency: 'urgent',
    status: 'active',
    targetAmountSOL: 5.8,
    raisedAmountSOL: 4.1,
    donorCount: 35,
    itemsNeeded: [
      { id: 'i-26', name: 'Pediatric Antibiotics & Inhalers', quantity: 60, unit: 'kits', fulfilled: true, estimatedCostUSD: 1200 },
      { id: 'i-27', name: 'Infant Formula & Clean Electrolytes', quantity: 100, unit: 'packs', fulfilled: false, estimatedCostUSD: 850 }
    ],
    audioDurationSec: 24,
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-09-05T11:30:00Z',
    tags: ['BeirutAid', 'MedicalRelief', 'PediatricCare', 'SolarHealth']
  },
  {
    id: 'req-011',
    title: 'दिल्ली समुदाय रसोई: स्वच्छ पेयजल एवं पौष्टिक भोजन (Delhi Clean Water & Food)',
    description: 'हमारी सामुदायिक रसोई दिल्ली में 300 से अधिक दिहाड़ी परिवारों को दैनिक स्वच्छ पेयजल और पौष्टिक गर्म भोजन उपलब्ध कराने हेतु सहयोग मांगती है।',
    authorName: 'Aarav Sharma',
    authorRole: 'कम्युनिटी सेवा समन्वयक',
    location: 'New Delhi, Delhi, India',
    coordinates: { lat: 28.6139, lng: 77.2090 },
    nonprofitName: 'Feeding America / Global Partner',
    nonprofitEin: '36-3673599',
    is501c3Verified: true,
    recipientWallet: 'FfFF5M2HFYT6Uir5hYVCE4sCa5yBLGqf4ckCuSHTxvS1',
    originalLanguage: 'hi-IN',
    originalLanguageLabel: 'हिन्दी',
    originalTranscript: 'हमारी सामुदायिक रसोई दिल्ली में 300 से अधिक परिवारों को दैनिक स्वच्छ पेयजल और पौष्टिक गर्म भोजन उपलब्ध कराती है।',
    voiceNarrationOriginal: 'हमारी सामुदायिक रसोई दिल्ली में 300 से अधिक दिहाड़ी परिवारों को दैनिक स्वच्छ पेयजल और पौष्टिक गर्म भोजन उपलब्ध कराने हेतु सहयोग मांगती है।',
    voiceNarrationEnglish: 'Our community solidarity kitchen in Delhi provides daily reverse-osmosis clean water and warm nutritious meals to over 300 wage-earner families.',
    voiceNarrationText: 'Our community solidarity kitchen in Delhi provides daily reverse-osmosis clean water and warm nutritious meals to over 300 wage-earner families.',
    climateData: {
      temperatureC: 32.4,
      temperatureF: 90.3,
      apparentTemperatureC: 36.2,
      humidity: 74,
      precipitationMm: 0,
      windSpeedKmh: 10.5,
      weatherCondition: 'Hazy Sun',
      weatherCode: 2,
      alertBadge: 'Heat Hydration Alert',
      alertLevel: 'extreme_heat',
      lastUpdated: new Date().toISOString(),
      source: 'Open-Meteo Live Climate Feed'
    },
    category: 'Food & Nutrition',
    unTheme: 'Ethical Giving',
    urgency: 'ongoing',
    status: 'active',
    targetAmountSOL: 3.8,
    raisedAmountSOL: 2.4,
    donorCount: 29,
    itemsNeeded: [
      { id: 'i-28', name: 'Commercial RO Water Filtration Cartridges', quantity: 4, unit: 'filters', fulfilled: true, estimatedCostUSD: 500 },
      { id: 'i-29', name: 'Grain & Lentil Sacks (100kg)', quantity: 10, unit: 'sacks', fulfilled: false, estimatedCostUSD: 650 }
    ],
    audioDurationSec: 23,
    imageUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2026-09-05T14:45:00Z',
    tags: ['DelhiSeva', 'CleanWater', 'FoodSecurity', 'MutualAid']
  }
];

export const DEVNET_VERIFIED_VAULTS = [
  'J5Q5PG75xeeFecNriPj4FEXuK5qcVz6sZjYTDh2rpZDG',
  'Dqv5yZzi8vN2TGsQ966CebKnsvBf12PXJEcvFTHdx1xu',
  '2VyJghegXGD7rPxS5HzemSWWjv64N8v8bThJoMRmTeEs',
  '7nuCn1x9RRGj9yhWPa8WwSVneJdMqU4tHHPsfdr3A17t',
  'D4MKCKqZTABJzneg5JiMxg2RqkBhdwcPWny92uVNomyH',
  '4aoR48sXEwyWEh9eUKzGV536CZzwSocHP5MAsX8WWJvD',
  'Afoem182Bdp1HK2ntS6iQQWkx1Wd8MBFLD2nkGpaWQAq',
  '6esP1E63SSeQsTkMAzqBB2YrZrLAD59PcwPhva89K1RX',
  '4P8DizCXxQJFHWU7BHJztDcQpD9B2Qz9r7tD2u9qsVPG',
  'CPDZcAs36XSyWQLqrkg3htNkHEpdLQ9GGyD6Fhgji2Wm',
  'FfFF5M2HFYT6Uir5hYVCE4sCa5yBLGqf4ckCuSHTxvS1'
];

export const DEFAULT_GRANTS = [
  {
    id: "grant-e2e-seed-001",
    requestId: "req-004",
    requestTitle: "Fresh Farm Produce Rescue & Community Solidarity Kitchen",
    donorName: "Elena & Global Solidarity Collective",
    amountSOL: 0.5,
    amountUSD: 51.15,
    txSignature: "5teRmiF5RDQA9GtCarm5GLJrPghmTWQRCohin6c9K9qfY45h11rNmGKikrJUmpy4xhXvKmu9Nie4jPW9waokki4p",
    slot: 494440484,
    blockTime: 1788771448,
    confirmationStatus: "confirmed",
    isOnChain: true,
    recipientWallet: "D4MKCKqZTABJzneg5JiMxg2RqkBhdwcPWny92uVNomyH",
    explorerUrl: "https://explorer.solana.com/tx/5teRmiF5RDQA9GtCarm5GLJrPghmTWQRCohin6c9K9qfY45h11rNmGKikrJUmpy4xhXvKmu9Nie4jPW9waokki4p?cluster=devnet",
    solscanUrl: "https://solscan.io/tx/5teRmiF5RDQA9GtCarm5GLJrPghmTWQRCohin6c9K9qfY45h11rNmGKikrJUmpy4xhXvKmu9Nie4jPW9waokki4p?cluster=devnet",
    timestamp: "2026-09-07T08:57:28.308Z",
    message: "Solidarity micro-grant for community organic vegetable distribution.",
    isEscrowLocked: false
  },
  {
    id: "grant-init-1",
    requestId: "req-001",
    requestTitle: "Warm Winter Coats & Thermal Boots for Ward 4 Children",
    donorName: "Anonymous Giver",
    amountSOL: 0.5,
    amountUSD: 72.5,
    txSignature: "bEQu49ziff6mr5xRTsPAMmuSeiG77bq5L1kbKFVk7j6pibR91p2s4p8LAmx1gA3WcgvWnEJunGqMGxAVc61sYXi",
    slot: 494502603,
    blockTime: 1788770700,
    confirmationStatus: "confirmed",
    isOnChain: true,
    recipientWallet: "Dqv5yZzi8vN2TGsQ966CebKnsvBf12PXJEcvFTHdx1xu",
    explorerUrl: "https://explorer.solana.com/tx/bEQu49ziff6mr5xRTsPAMmuSeiG77bq5L1kbKFVk7j6pibR91p2s4p8LAmx1gA3WcgvWnEJunGqMGxAVc61sYXi?cluster=devnet",
    solscanUrl: "https://solscan.io/tx/bEQu49ziff6mr5xRTsPAMmuSeiG77bq5L1kbKFVk7j6pibR91p2s4p8LAmx1gA3WcgvWnEJunGqMGxAVc61sYXi?cluster=devnet",
    timestamp: "2026-09-03T18:40:00Z",
    message: "Stay warm kids!",
    isEscrowLocked: true
  },
  {
    id: "grant-init-2",
    requestId: "req-002",
    requestTitle: "Emergency Solar Backup Battery for Appalachian Mountain Clinic",
    donorName: "SolarHope Guild",
    amountSOL: 1,
    amountUSD: 145,
    txSignature: "5352WbH55nHWcVwmHokL97hg1FNBLLkUfMfCmwuceU46zPKcZmbGvpsp2jksSuwUEPQZDkgvyj3HbT3W1fpzGwH4",
    slot: 494502602,
    blockTime: 1788770695,
    confirmationStatus: "confirmed",
    isOnChain: true,
    recipientWallet: "2VyJghegXGD7rPxS5HzemSWWjv64N8v8bThJoMRmTeEs",
    explorerUrl: "https://explorer.solana.com/tx/5352WbH55nHWcVwmHokL97hg1FNBLLkUfMfCmwuceU46zPKcZmbGvpsp2jksSuwUEPQZDkgvyj3HbT3W1fpzGwH4?cluster=devnet",
    solscanUrl: "https://solscan.io/tx/5352WbH55nHWcVwmHokL97hg1FNBLLkUfMfCmwuceU46zPKcZmbGvpsp2jksSuwUEPQZDkgvyj3HbT3W1fpzGwH4?cluster=devnet",
    timestamp: "2026-09-03T21:10:00Z",
    message: "Keep that medicine cold. You are heroes.",
    isEscrowLocked: true
  }
];
